### ISSUE TITLE
`KeyError: /api/logical-partitions/XXXX` followed by `AssertionError: No CPC Found`

### ISSUE THREAD

**Issue by vmorris** [zhmcclient/zhmc-prometheus-exporter#113] opened 2021-03-11 03:49 UTC
Attempting to use this tool against a z13 HMC, and it's failing with the following stack trace.
**I am able to use the python hmcclient to interact with the HMC without any errors.**

- HMC version : 2.14.0
- Buncle level: H41
- Machine type: 2964
- Model type: L63

```
$ pip show zhmc-prometheus-exporter
Name: zhmc-prometheus-exporter
Version: 0.6.0
```

```
Traceback (most recent call last):
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 432, in resource
    _resource = self._resources[uri]
KeyError: '/api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
    output = encoder(registry)
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 589, in collect
    family_objects = build_family_objects(metrics_object,
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 467, in build_family_objects
    resource = resource_cache.resource(
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 435, in resource
    _resource = object_value.resource  # Takes time to find on HMC
  File "/home/fedora/zhmc-prometheus-exporter/lib64/python3.9/site-packages/zhmcclient/_metrics.py", line 875, in resource
    raise AssertionError("No CPC found")
AssertionError: No CPC found
```

**Comment by andy-maier** [comment] 2021-03-12 07:57
That is an unexpected situation, but the assertion error message unfortunately does not provide enough information to be able to fix the situation. I'll improve the assertion message, and then a reproduction would be good. Stay tuned.

**Comment by andy-maier** [comment] 2021-03-15 08:08
@vmorris Vance, I did some investigation, but I may not have the solution yet. This seems to be a mismatch between the resource that was referenced in the metric delivered by the HMC, and the actual presence of that resource as reported by the HMC. The resource is an LPAR, which apparently does not exist (as per the HMC) at the time the exporter attempts to get its properties. The exporter does that once initially for maintaining a resource cache, and then lateron when metrics reference new resources that are not yet in the resource cache. So it appears to me at this point that a metric referenced this LPAR, the LPAR was not in the cache, but the HMC did not know this LPAR when its properties were attempted to be retrieved.

One possible way this could have happened is if the LPAR was newly created and the HMC already delivered metrics for it but had the LPAR not yet in the state where it was able to deliver its properties.

Can you find out whether an LPAR was created around the time the error happened? Or deleted?

I am in the process of updating zhmcclient and the exporter for better error handling and debug data for this situation, but this will take a couple more days to get it reviewed.

In the mean time, can you please run the exporter with `-vv` and see whether you can reproduce the error, using both zhmcclient and the exporter from their master branches?

**Comment by vmorris** [comment] 2021-03-15 13:40
> Can you find out whether an LPAR was created around the time the error happened? Or deleted?

I'm pretty sure this is not the case.. I'm still seeing the problem today, and as far as I know there haven't been any LPARs created or deleted on this machine in years.


I reproduced the issue with the latest code from both repo's master branch:
```
vmorris@tpp53:~ $ python -m venv ~/venvs/export_issue_4

vmorris@tpp53:~ $ . ~/venvs/export_issue_4/bin/activate
(export_issue_4)vmorris@tpp53:~ $ pip install --upgrade pip
>>> OUTPUT REMOVED <<<
Successfully installed pip-21.0.1

(export_issue_4)vmorris@tpp53:~ $ pip install git+https://github.com/zhmcclient/python-zhmcclient.git
>>> OUTPUT REMOVED <<<
Successfully installed certifi-2020.12.5 chardet-4.0.0 decorator-4.4.2 docopt-0.6.2 idna-2.10 pytz-2021.1 requests-2.25.1 six-1.15.0 stomp.py-6.1.0 urllib3-1.26.3 zhmcclient-0.29.0.dev1

(export_issue_4)vmorris@tpp53:~ $ pip install git+https://github.com/zhmcclient/zhmc-prometheus-exporter.git
>>> OUTPUT REMOVED <<<
Successfully installed PyYAML-5.4.1 attrs-20.3.0 jsonschema-3.2.0 prometheus-client-0.9.0 pyrsistent-0.17.3 zhmc-prometheus-exporter-0.7.0.dev1

(export_issue_4)vmorris@tpp53:~ $ zhmc_prometheus_exporter -vv -c ~/prom/zhmc-prometheus-exporter/rduz13_hmccreds.yml -m prom/zhmc-prometheus-exporter/metrics.yaml -p 9292
Parsing HMC credentials file: /home/vmorris/prom/zhmc-prometheus-exporter/rduz13_hmccreds.yml
Parsing metric definition file: prom/zhmc-prometheus-exporter/metrics.yaml
Creating a session with HMC 10.0.5.83
HMC version: 2.14.0
Creating a metrics context on the HMC for metric groups:
  cpc-usage-overview
  logical-partition-usage
  channel-usage
  crypto-usage
  flash-memory-usage
  roce-usage
  dpm-system-usage-overview
  partition-usage
  adapter-usage
  network-physical-adapter-port
  zcpc-environmentals-and-power
  zcpc-processor-usage
Using extra labels: 
Registering the collector and performing first collection
Collecting metrics
Fetching metrics from HMC
Building family objects
Returning family objects
Done collecting metrics
Starting the HTTP server on port 9292
Exporter is up and running
Collecting metrics
Fetching metrics from HMC
Building family objects
Finding resource for /api/cpcs/74557ca2-9ee5-3dd8-b88c-07d76fca02c9
Finding resource for /api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884
Traceback (most recent call last):
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 432, in resource
    _resource = self._resources[uri]
KeyError: '/api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 87, in zhmc_exceptions
    yield
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 589, in collect
    family_objects = build_family_objects(metrics_object,
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 467, in build_family_objects
    resource = resource_cache.resource(
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 435, in resource
    _resource = object_value.resource  # Takes time to find on HMC
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmcclient/_metrics.py", line 895, in resource
    raise MetricsResourceNotFound(
zhmcclient._exceptions.MetricsResourceNotFound: logical-partition with URI /api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884 not found in CPCs P1020304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
    output = encoder(registry)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 589, in collect
    family_objects = build_family_objects(metrics_object,
  File "/usr/lib64/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 99, in zhmc_exceptions
    raise OtherError("Error returned from HMC at {}: {}".
zhmc_prometheus_exporter.zhmc_prometheus_exporter.OtherError: Error returned from HMC at 10.0.5.83: logical-partition with URI /api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884 not found in CPCs P1020304
^CExporter interrupted after server start.
```

**Comment by andy-maier** [comment] 2021-03-15 16:34
Ok. Thanks for checking.

I have merged a PR to the exporter's master branch since then, that prints some more information. Could you please update the installation to pick up the latest master branch?

Also, could you please list the LPARs with their URIs, e.g. with:
```
$ zhmc lpar list P1020304 --names-only --uri
```

**Comment by andy-maier** [comment] 2021-03-15 16:40
What is quite strange in the output you posted is that the exporter does not fetch any resources in the initial collection:
```
Collecting metrics
Fetching metrics from HMC
Building family objects
# <-- Would have expected 'Finding resource for ...' 
Returning family objects
Done collecting metrics
```
When I run the exporter, it finds all resources referenced by the initial metrics returned, during the initial cycle.
It seems like the initial cycle does not return any metrics yet.

**Comment by vmorris** [comment] 2021-03-15 16:48
Here's the latest run output:
```
(export_issue_4)vmorris@tpp53:~ $ zhmc_prometheus_exporter -vv -c ~/prom/zhmc-prometheus-exporter/rduz13_hmccreds.yml -m prom/zhmc-prometheus-exporter/metrics.yaml -p 9292

Parsing HMC credentials file: /home/vmorris/prom/zhmc-prometheus-exporter/rduz13_hmccreds.yml
Parsing metric definition file: prom/zhmc-prometheus-exporter/metrics.yaml
Creating a session with HMC 10.0.5.83
HMC version: 2.14.0
Creating a metrics context on the HMC for metric groups:
  cpc-usage-overview
  logical-partition-usage
  channel-usage
  crypto-usage
  flash-memory-usage
  roce-usage
  dpm-system-usage-overview
  partition-usage
  adapter-usage
  network-physical-adapter-port
  zcpc-environmentals-and-power
  zcpc-processor-usage
Using extra labels: 
Registering the collector and performing first collection
Collecting metrics
Fetching metrics from HMC
Building family objects
Returning family objects
Done collecting metrics
Starting the HTTP server on port 9292
Exporter is up and running
Collecting metrics
Fetching metrics from HMC
Building family objects
Returning family objects
Done collecting metrics
Collecting metrics
Fetching metrics from HMC
Building family objects
Finding resource for /api/cpcs/74557ca2-9ee5-3dd8-b88c-07d76fca02c9
Finding resource for /api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884
Debug: Dump of current resource cache in exporter:
['/api/cpcs/74557ca2-9ee5-3dd8-b88c-07d76fca02c9']
Debug: List of resources found:
['/api/logical-partitions/01b2c936-f48c-3be0-a62e-089a30d81ba6',
 '/api/logical-partitions/01fc88b7-25e5-3f03-a729-4726ec50c2ab',
 '/api/logical-partitions/03203468-965e-3820-acfe-a6de574c44da',
 '/api/logical-partitions/03ab2bb7-c302-395d-98b3-3faf4f863f2c',
 '/api/logical-partitions/03c5ec22-adca-34c1-970b-314e8dd826b3',
 '/api/logical-partitions/0970bd87-0d9c-3578-bc8c-107e45cec46b',
 '/api/logical-partitions/10c75347-52cd-3e98-8540-60ca628804a6',
 '/api/logical-partitions/15c7548a-39d7-3db5-8313-c4b4e3e61bc1',
 '/api/logical-partitions/15d3d1a4-58c6-33b9-8389-b2e4f95de942',
 '/api/logical-partitions/17462b86-ba5b-35db-b17c-78be699147b4',
 '/api/logical-partitions/1a72b676-3678-3441-80c7-960ea2b95e0b',
 '/api/logical-partitions/2f22137b-ae61-3938-9e48-b898875879c2',
 '/api/logical-partitions/33056216-82e7-33e0-84dd-2553c9e68bce',
 '/api/logical-partitions/34795409-9875-34d0-a748-96f5c1dd48e6',
 '/api/logical-partitions/3c42cf4a-303d-3ad4-b730-5e11b7f96abd',
 '/api/logical-partitions/3ea35b9a-d7da-36bb-85d7-95bdbc370bdf',
 '/api/logical-partitions/405d4d30-11b0-3ee5-835f-b3de261c52c0',
 '/api/logical-partitions/48ae5844-6b72-3813-8719-26371bee3ed7',
 '/api/logical-partitions/4a01291a-5863-33c7-9747-75be04bc7015',
 '/api/logical-partitions/4f75f133-0982-382c-82b4-1e6ef285303e',
 '/api/logical-partitions/52c1c455-e37f-35ff-a840-ca8977406b86',
 '/api/logical-partitions/55771fa8-60f1-3483-b390-f0c7c0a74dd1',
 '/api/logical-partitions/58e7f67f-a0d2-3b70-bb75-6633dfd11181',
 '/api/logical-partitions/59f92860-db75-3b35-bc9d-67b1a8e6fcd9',
 '/api/logical-partitions/5c78f883-e090-3b1f-9254-9c3e7f6a2ec1',
 '/api/logical-partitions/718b5309-4283-3b27-b915-604f1a41f88b',
 '/api/logical-partitions/82a87145-7655-35ff-a24d-4318651ba7b7',
 '/api/logical-partitions/8694336d-763c-3382-93f1-2ddfe5cada5e',
 '/api/logical-partitions/948bc444-9400-3251-9e61-e927f5f51e3c',
 '/api/logical-partitions/95643fbc-b503-365a-8a3e-ccbdbb759a93',
 '/api/logical-partitions/a029f9f5-a810-3964-b3ca-2be42388e249',
 '/api/logical-partitions/a062fc1c-4600-3c24-ba2b-fd318a261ee6',
 '/api/logical-partitions/a2daa68d-9316-32be-83c0-b7e8836c2dec',
 '/api/logical-partitions/a710d75f-383e-31af-bbc6-cdbdd2609ba7',
 '/api/logical-partitions/a7b9fe0c-96b1-3315-a446-e3e8fb640e7a',
 '/api/logical-partitions/aea6bc9c-954a-335f-a4ce-23057b704b34',
 '/api/logical-partitions/aefb85be-b9ea-339b-81f0-9ea14a5f1216',
 '/api/logical-partitions/b1396f0c-3b3f-34bf-9cf2-b0e73ad70cbf',
 '/api/logical-partitions/b2ef5d87-1b23-3529-90dc-1c69ca7f56ea',
 '/api/logical-partitions/b5aa1e33-007b-35be-b3b2-a23376538f9c',
 '/api/logical-partitions/b60aa231-4dae-301c-9311-580b32e15437',
 '/api/logical-partitions/b666b0d1-8fb0-3ab9-a2e4-ea85e2aa2b16',
 '/api/logical-partitions/b87af4d3-169e-3481-a952-51aa24a8a33b',
 '/api/logical-partitions/bc93cef0-5d3d-3db5-972d-a8dfb67f7c98',
 '/api/logical-partitions/bf104b2b-0de0-342b-8daf-b41fe5378bf9',
 '/api/logical-partitions/ce73cc21-b14e-379f-94ad-232eb532d3d9',
 '/api/logical-partitions/ced18260-bc16-3372-a603-bf0267561028',
 '/api/logical-partitions/d4bcea3d-d50a-392f-be30-0eeb49311e90',
 '/api/logical-partitions/da30ec3c-513f-36b3-820b-a8c8a442b241',
 '/api/logical-partitions/db8864ab-f799-3b1a-a2b0-d664a3ab7242',
 '/api/logical-partitions/de1d8993-fc0b-3388-bf95-5128aaf4c2cc',
 '/api/logical-partitions/e0c8b533-16b4-3ad4-b517-a0441f2a2f16',
 '/api/logical-partitions/e2585455-e9e8-3c13-94dd-7db1c639e24c',
 '/api/logical-partitions/e89a3953-95c5-315f-868c-0db68361aa0d',
 '/api/logical-partitions/e996e871-a42e-3c2a-9b1a-f66821d9cab3',
 '/api/logical-partitions/ecd939c8-e7d7-3a9d-b5cf-8a1114cf3eb2',
 '/api/logical-partitions/ef83fe8c-a7cf-3456-a5dc-f5557bb07ee1',
 '/api/logical-partitions/f1f7bffa-e669-3b66-8042-6e6c9756353f',
 '/api/logical-partitions/f28f7499-0e35-3d61-9bce-095ca555736c',
 '/api/logical-partitions/ff5867df-aae5-36d3-9719-1eb310f8c549']
Traceback (most recent call last):
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 433, in resource
    _resource = self._resources[uri]
KeyError: '/api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 88, in zhmc_exceptions
    yield
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 603, in collect
    family_objects = build_family_objects(metrics_object,
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 481, in build_family_objects
    resource = resource_cache.resource(
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 437, in resource
    _resource = object_value.resource  # Takes time to find on HMC
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmcclient/_metrics.py", line 895, in resource
    raise MetricsResourceNotFound(
zhmcclient._exceptions.MetricsResourceNotFound: logical-partition with URI /api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884 not found in CPCs P1020304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
    output = encoder(registry)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 603, in collect
    family_objects = build_family_objects(metrics_object,
  File "/usr/lib64/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/vmorris/venvs/export_issue_4/lib64/python3.9/site-packages/zhmc_prometheus_exporter/zhmc_prometheus_exporter.py", line 100, in zhmc_exceptions
    raise OtherError("Error returned from HMC at {}: {}".
zhmc_prometheus_exporter.zhmc_prometheus_exporter.OtherError: Error returned from HMC at 10.0.5.83: logical-partition with URI /api/logical-partitions/78841a4f-1076-31f8-b9dd-78a0b7b42884 not found in CPCs P1020304
^CExporter interrupted after server start.
```

`$ zhmc lpar list P1020304 --names-only --uri` returns `Error: no such option: --names-only`.

Perhaps I have this utility out of date... trying without the --names-only I get back:

```
vmorris@tpp53:~ $ zhmc lpar list P1020304 --uri
+--------+---------------+--------------------------------------------------------------+
| name   | status        | object-uri                                                   |
|--------+---------------+--------------------------------------------------------------|
| L01    | operating     | /api/logical-partitions/59f92860-db75-3b35-bc9d-67b1a8e6fcd9 |
| L02    | operating     | /api/logical-partitions/58e7f67f-a0d2-3b70-bb75-6633dfd11181 |
| L03    | operating     | /api/logical-partitions/405d4d30-11b0-3ee5-835f-b3de261c52c0 |
| L04    | operating     | /api/logical-partitions/33056216-82e7-33e0-84dd-2553c9e68bce |
| L05    | operating     | /api/logical-partitions/03ab2bb7-c302-395d-98b3-3faf4f863f2c |
| L06    | operating     | /api/logical-partitions/db8864ab-f799-3b1a-a2b0-d664a3ab7242 |
| L07    | operating     | /api/logical-partitions/5c78f883-e090-3b1f-9254-9c3e7f6a2ec1 |
| L08    | not-activated | /api/logical-partitions/b5aa1e33-007b-35be-b3b2-a23376538f9c |
| L09    | not-activated | /api/logical-partitions/b87af4d3-169e-3481-a952-51aa24a8a33b |
| L0A    | not-activated | /api/logical-partitions/03203468-965e-3820-acfe-a6de574c44da |
| L0B    | not-activated | /api/logical-partitions/a2daa68d-9316-32be-83c0-b7e8836c2dec |
| L0C    | not-activated | /api/logical-partitions/b2ef5d87-1b23-3529-90dc-1c69ca7f56ea |
| L0D    | not-activated | /api/logical-partitions/ecd939c8-e7d7-3a9d-b5cf-8a1114cf3eb2 |
| L0E    | not-activated | /api/logical-partitions/f28f7499-0e35-3d61-9bce-095ca555736c |
| L11    | not-activated | /api/logical-partitions/e996e871-a42e-3c2a-9b1a-f66821d9cab3 |
| L12    | not-activated | /api/logical-partitions/1a72b676-3678-3441-80c7-960ea2b95e0b |
| L13    | not-activated | /api/logical-partitions/e0c8b533-16b4-3ad4-b517-a0441f2a2f16 |
| L14    | not-activated | /api/logical-partitions/2f22137b-ae61-3938-9e48-b898875879c2 |
| L15    | not-activated | /api/logical-partitions/da30ec3c-513f-36b3-820b-a8c8a442b241 |
| L16    | not-activated | /api/logical-partitions/95643fbc-b503-365a-8a3e-ccbdbb759a93 |
| L17    | not-activated | /api/logical-partitions/b666b0d1-8fb0-3ab9-a2e4-ea85e2aa2b16 |
| L18    | not-activated | /api/logical-partitions/34795409-9875-34d0-a748-96f5c1dd48e6 |
| L19    | not-activated | /api/logical-partitions/718b5309-4283-3b27-b915-604f1a41f88b |
| L1A    | not-activated | /api/logical-partitions/3ea35b9a-d7da-36bb-85d7-95bdbc370bdf |
| L1B    | not-activated | /api/logical-partitions/48ae5844-6b72-3813-8719-26371bee3ed7 |
| L1C    | not-activated | /api/logical-partitions/0970bd87-0d9c-3578-bc8c-107e45cec46b |
| L1D    | not-activated | /api/logical-partitions/e89a3953-95c5-315f-868c-0db68361aa0d |
| L1E    | not-activated | /api/logical-partitions/bc93cef0-5d3d-3db5-972d-a8dfb67f7c98 |
| L1F    | not-activated | /api/logical-partitions/52c1c455-e37f-35ff-a840-ca8977406b86 |
| L21    | operating     | /api/logical-partitions/15c7548a-39d7-3db5-8313-c4b4e3e61bc1 |
| L22    | not-activated | /api/logical-partitions/ced18260-bc16-3372-a603-bf0267561028 |
| L23    | not-activated | /api/logical-partitions/b60aa231-4dae-301c-9311-580b32e15437 |
| L24    | not-activated | /api/logical-partitions/ff5867df-aae5-36d3-9719-1eb310f8c549 |
| L25    | not-activated | /api/logical-partitions/8694336d-763c-3382-93f1-2ddfe5cada5e |
| L26    | not-activated | /api/logical-partitions/4f75f133-0982-382c-82b4-1e6ef285303e |
| L27    | not-activated | /api/logical-partitions/aea6bc9c-954a-335f-a4ce-23057b704b34 |
| L28    | not-activated | /api/logical-partitions/17462b86-ba5b-35db-b17c-78be699147b4 |
| L29    | not-activated | /api/logical-partitions/f1f7bffa-e669-3b66-8042-6e6c9756353f |
| L2A    | not-activated | /api/logical-partitions/a710d75f-383e-31af-bbc6-cdbdd2609ba7 |
| L2B    | not-activated | /api/logical-partitions/a7b9fe0c-96b1-3315-a446-e3e8fb640e7a |
| L2C    | not-activated | /api/logical-partitions/a062fc1c-4600-3c24-ba2b-fd318a261ee6 |
| L2D    | not-activated | /api/logical-partitions/15d3d1a4-58c6-33b9-8389-b2e4f95de942 |
| L2E    | not-activated | /api/logical-partitions/01b2c936-f48c-3be0-a62e-089a30d81ba6 |
| L2F    | not-activated | /api/logical-partitions/ef83fe8c-a7cf-3456-a5dc-f5557bb07ee1 |
| L31    | not-activated | /api/logical-partitions/4a01291a-5863-33c7-9747-75be04bc7015 |
| L32    | not-activated | /api/logical-partitions/55771fa8-60f1-3483-b390-f0c7c0a74dd1 |
| L33    | not-activated | /api/logical-partitions/bf104b2b-0de0-342b-8daf-b41fe5378bf9 |
| L34    | not-activated | /api/logical-partitions/03c5ec22-adca-34c1-970b-314e8dd826b3 |
| L35    | not-activated | /api/logical-partitions/948bc444-9400-3251-9e61-e927f5f51e3c |
| L36    | not-activated | /api/logical-partitions/de1d8993-fc0b-3388-bf95-5128aaf4c2cc |
| L37    | not-activated | /api/logical-partitions/01fc88b7-25e5-3f03-a729-4726ec50c2ab |
| L38    | not-activated | /api/logical-partitions/aefb85be-b9ea-339b-81f0-9ea14a5f1216 |
| L39    | not-activated | /api/logical-partitions/ce73cc21-b14e-379f-94ad-232eb532d3d9 |
| L3A    | not-activated | /api/logical-partitions/a029f9f5-a810-3964-b3ca-2be42388e249 |
| L3B    | not-activated | /api/logical-partitions/e2585455-e9e8-3c13-94dd-7db1c639e24c |
| L3C    | not-activated | /api/logical-partitions/b1396f0c-3b3f-34bf-9cf2-b0e73ad70cbf |
| L3D    | not-activated | /api/logical-partitions/3c42cf4a-303d-3ad4-b730-5e11b7f96abd |
| L3E    | not-activated | /api/logical-partitions/d4bcea3d-d50a-392f-be30-0eeb49311e90 |
| L3F    | not-activated | /api/logical-partitions/10c75347-52cd-3e98-8540-60ca628804a6 |
| S01    | operating     | /api/logical-partitions/82a87145-7655-35ff-a24d-4318651ba7b7 |
+--------+---------------+--------------------------------------------------------------+
```

**Comment by andy-maier** [comment] 2021-03-15 16:51
Ok, so the LPAR referenced by the metric data really does not exist on the CPC. I guess this calls for a PMR against the HMC. They very likely will need trace/dump data to investigate this, so please attach that to the PMR (if you need help in figuring out which dumps to send, let me know then I can ask the dev team).

**Comment by andy-maier** [comment] 2021-03-15 16:53
On the `--names-only` option: We added that to the zhmccli command to speed up its output because that avoids the loop of Get requests on the List result. It is in the master branch but not yet released. (See https://github.com/zhmcclient/zhmccli/blob/master/docs/changes.rst).

**Comment by vmorris** [comment] 2021-03-15 17:10
Thanks @andy-maier - I will take a look at reporting a problem through the HMC.

**Comment by andy-maier** [comment] 2021-03-15 20:23
I have just added support for logging the HMC interactions to a file. It requires an update from the master branch of the exporter, and PR https://github.com/zhmcclient/python-zhmcclient/pull/733 (not yet merged to master) of zhmcclient.

**Comment by andy-maier** [comment] 2021-03-16 09:18
@vmorris If and when you open a PMR, it would be good to attach a the log file created with the new `--log FILE` option, because that would show that the metrics response contains an LPAR URI that does not show up in the listed LPARs. Doing that requires using both the exporter and zhmcclient from its master branches.

**Comment by andy-maier** [comment] 2021-03-16 09:19
I've set this issue to pursued elsewhere, as it seems to be an HMC defect right now. Will keep this issue open for now.

**Comment by andy-maier** [comment] 2021-04-07 07:31
I am closing this issue. Feel free to reopen it or to open a new issue should it reoccur.

**Closed by andy-maier** 2021-04-07 07:31 UTC
Labels: area: code, resolution: delegated, type: bug

**Comment by vmorris** [comment] 2021-04-07 12:26
Thank you @andy-maier - I have a PMR open with the attached log file, awaiting some action from PE. I suspect the HMC will need to be upgraded, or at least restarted, and then perhaps the problem will simply disappear.

I'll open a new issue if I cannot make progress past that!
